import { ChapterData } from './ChapterItem';

export const levelCatalog: ChapterData[] = [
    {
        id: 1,
        name: '异世落地',
        titleBackgroundPath: 'LevelSelect/Chapter1',
        levels: [
            {
                id: 1,
                chapterId: 1,
                name: 'LV1.凡尘匿迹',
                iconPath: 'LevelSelect/LevelCover',
                unlocked: true,
                star: 0,
                target: 'Level1_1',
            },
            {
                id: 2,
                chapterId: 1,
                name: 'LV2.山野觅食',
                iconPath: 'LevelSelect/LevelCover',
                unlocked: false,
                star: 0,
                target: 'Level1_2',
            },
            {
                id: 3,
                chapterId: 1,
                name: 'LV3.拾薪过夜',
                iconPath: 'LevelSelect/LevelCover',
                unlocked: false,
                star: 0,
                target: 'Level1_3',
            },
            {
                id: 4,
                chapterId: 1,
                name: 'LV4.消迹藏物',
                iconPath: 'LevelSelect/LevelCover',
                unlocked: false,
                star: 0,
                target: 'Level1_4',
            },
            {
                id: 5,
                chapterId: 1,
                name: 'LV5.寻屋栖身',
                iconPath: 'LevelSelect/LevelCover',
                unlocked: false,
                star: 0,
                target: 'Level1_5',
            },
            {
                id: 6,
                chapterId: 1,
                name: 'LV6.修葺陋室',
                iconPath: 'LevelSelect/LevelCover',
                unlocked: false,
                star: 0,
                target: 'Level1_6',
            },
        ],
    },
    {
        id: 2,
        name: '仙门初试',
        titleBackgroundPath: 'LevelSelect/Chapter2',
        levels: [
            {
                id: 1,
                chapterId: 2,
                name: 'LV1.凡尘匿迹',
                iconPath: 'LevelSelect/LevelCover',
                unlocked: false,
                star: 0,
                target: 'Level2_1',
            },
            {
                id: 2,
                chapterId: 2,
                name: 'LV2.山野览食',
                iconPath: 'LevelSelect/LevelCover',
                unlocked: false,
                star: 0,
                target: 'Level2_2',
            },
        ],
    },
];
